sudo: required
language: go
go: master

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]
    then
      ./build.sh
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push antihax/eve-marketwatch
    fi